CREATE TABLE "SYS_OPER_LOG" (
    "OPER_ID" BIGINT AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50 CHAR) DEFAULT '',
    "BUSINESS_TYPE" INT DEFAULT 0,
    "METHOD" VARCHAR(200 CHAR) DEFAULT '',
    "REQUEST_METHOD" VARCHAR(10 CHAR) DEFAULT '',
    "OPERATOR_TYPE" INT DEFAULT 0,
    "OPER_NAME" VARCHAR(50 CHAR) DEFAULT '',
    "DEPT_NAME" VARCHAR(50 CHAR) DEFAULT '',
    "OPER_URL" VARCHAR(255 CHAR) DEFAULT '',
    "OPER_IP" VARCHAR(128 CHAR) DEFAULT '',
    "OPER_LOCATION" VARCHAR(255 CHAR) DEFAULT '',
    "OPER_PARAM" CLOB,
    "JSON_RESULT" VARCHAR(2000 CHAR) DEFAULT '',
    "STATUS" INT DEFAULT 0,
    "ERROR_MSG" VARCHAR(2000 CHAR) DEFAULT '',
    "OPER_TIME" TIMESTAMP(0),
    "COST_TIME" BIGINT DEFAULT 0,
    "CREATE_BY" VARCHAR(50 CHAR) DEFAULT '',
    "CREATE_TIME" TIMESTAMP(0),
    CONSTRAINT "SYS_OPER_LOG_PRIMARY" NOT CLUSTER PRIMARY KEY ("OPER_ID")
)
    STORAGE (ON "MAIN", CLUSTERBTR) AUTO_INCREMENT = 1;

CREATE OR REPLACE INDEX "idx_SYS_OPER_LOG_ot" ON "SYS_OPER_LOG"(
    "OPER_TIME" ASC
)
STORAGE (ON "MAIN", CLUSTERBTR);

CREATE OR REPLACE INDEX "idx_SYS_OPER_LOG_bt" ON "SYS_OPER_LOG"(
    "BUSINESS_TYPE" ASC
)
STORAGE (ON "MAIN", CLUSTERBTR);

CREATE OR REPLACE INDEX "idx_SYS_OPER_LOG_s" ON "SYS_OPER_LOG"(
    "STATUS" ASC
)
STORAGE (ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE "SYS_OPER_LOG" IS '操作日志记录';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_ID" IS '日志主键';

COMMENT ON COLUMN "SYS_OPER_LOG"."TITLE" IS '模块标题';

COMMENT ON COLUMN "SYS_OPER_LOG"."BUSINESS_TYPE" IS '业务类型（0其它 1新增 2修改 3删除）';

COMMENT ON COLUMN "SYS_OPER_LOG"."METHOD" IS '方法名称';

COMMENT ON COLUMN "SYS_OPER_LOG"."REQUEST_METHOD" IS '请求方式';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPERATOR_TYPE" IS '操作类别（0其它 1后台用户 2手机端用户）';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_NAME" IS '操作人员';

COMMENT ON COLUMN "SYS_OPER_LOG"."DEPT_NAME" IS '部门名称';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_URL" IS '请求URL';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_IP" IS '主机地址';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_LOCATION" IS '操作地点';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_PARAM" IS '请求参数';

COMMENT ON COLUMN "SYS_OPER_LOG"."JSON_RESULT" IS '返回参数';

COMMENT ON COLUMN "SYS_OPER_LOG"."STATUS" IS '操作状态（0正常 1异常）';

COMMENT ON COLUMN "SYS_OPER_LOG"."ERROR_MSG" IS '错误消息';

COMMENT ON COLUMN "SYS_OPER_LOG"."OPER_TIME" IS '操作时间';

COMMENT ON COLUMN "SYS_OPER_LOG"."COST_TIME" IS '消耗时间';

COMMENT ON COLUMN "SYS_OPER_LOG"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "SYS_OPER_LOG"."CREATE_TIME" IS '创建时间';

SET IDENTITY_INSERT "SYS_MENU" ON;
INSERT INTO "SYS_MENU"("MENU_ID","PID","SUB_COUNT","TYPE","TITLE","NAME","COMPONENT","MENU_SORT","ICON","PATH","I_FRAME","CACHE","HIDDEN","PERMISSION","CREATE_BY","UPDATE_BY","CREATE_TIME","UPDATE_TIME")
VALUES(110, 1, 0, 1, '操作日志', 'system-log', 'system/log/index', 4, 'password', 'system-log', '0', '0', '0', 'log:read', NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT "SYS_MENU" OFF;
