ALTER TABLE `sys_menu`
    ADD COLUMN `is_plugin` bit(1) NULL DEFAULT b'0' AFTER `hidden`;

INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (4, 1, 0, 1, '组织管理', 'system-dept', 'system/dept/index', 3, 'dept', 'dept', b'1', b'0', b'0', b'0', 'dept:read', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (5, 1, 0, 1, '角色管理', 'system-role', 'system/role/index', 2, 'role', 'role', b'1', b'0', b'0', b'0', 'role:read', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (18, 4, 0, 2, '创建组织', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'1', 'dept:add', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (19, 4, 0, 2, '删除组织', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'1', 'dept:del', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (20, 4, 0, 2, '修改组织', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'1', 'dept:edit', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (21, 5, 0, 2, '创建角色', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'0', 'role:add', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (22, 5, 0, 2, '删除角色', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'0', 'role:del', NULL, NULL, NULL, NULL);
INSERT INTO `sys_menu` (`menu_id`, `pid`, `sub_count`, `type`, `title`, `name`, `component`, `menu_sort`, `icon`, `path`, `i_frame`, `cache`, `hidden`, `is_plugin`, `permission`, `create_by`, `update_by`, `create_time`, `update_time`) VALUES (23, 5, 0, 2, '修改角色', NULL, NULL, 999, NULL, NULL, b'0', b'0', b'0', b'0', 'role:edit', NULL, NULL, NULL, NULL);
