ALTER TABLE "USER_KEY" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "USER_KEY" ADD CONSTRAINT "IDX_AK" UNIQUE("ACCESS_KEY") ;

ALTER TABLE "SYS_USERS_ROLES" ADD CONSTRAINT  PRIMARY KEY("USER_ID","ROLE_ID") ;

ALTER TABLE "SYS_USER" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;

ALTER TABLE "SYS_THEME" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "SYS_TASK_INSTANCE" ADD CONSTRAINT  PRIMARY KEY("INSTANCE_ID") ;

ALTER TABLE "SYS_TASK_EMAIL" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "SYS_TASK" ADD CONSTRAINT  PRIMARY KEY("TASK_ID") ;

ALTER TABLE "SYS_ROLES_MENUS" ADD CONSTRAINT  PRIMARY KEY("MENU_ID","ROLE_ID") ;

ALTER TABLE "SYS_ROLE" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID") ;

ALTER TABLE "SYS_MSG_TYPE" ADD CONSTRAINT  PRIMARY KEY("MSG_TYPE_ID") ;

ALTER TABLE "SYS_MSG_SETTING" ADD CONSTRAINT  PRIMARY KEY("MSG_SETTING_ID") ;

ALTER TABLE "SYS_MSG_CHANNEL" ADD CONSTRAINT  PRIMARY KEY("MSG_CHANNEL_ID") ;

ALTER TABLE "SYS_MSG" ADD CONSTRAINT  PRIMARY KEY("MSG_ID") ;

ALTER TABLE "SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;

ALTER TABLE "SYS_DEPT" ADD CONSTRAINT  PRIMARY KEY("DEPT_ID") ;

ALTER TABLE "SYS_BACKGROUND_IMAGE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "SYS_AUTH_DETAIL" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "SYS_AUTH" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "SYSTEM_PARAMETER" ADD CONSTRAINT  PRIMARY KEY("PARAM_KEY") ;

ALTER TABLE "SCHEDULE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "QRTZ_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ;

ALTER TABLE "QRTZ_SIMPROP_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ;

ALTER TABLE "QRTZ_SIMPLE_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ;

ALTER TABLE "QRTZ_SCHEDULER_STATE" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","INSTANCE_NAME") ;

ALTER TABLE "QRTZ_PAUSED_TRIGGER_GRPS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_GROUP") ;

ALTER TABLE "QRTZ_LOCKS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","LOCK_NAME") ;

ALTER TABLE "QRTZ_JOB_DETAILS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","JOB_NAME","JOB_GROUP") ;

ALTER TABLE "QRTZ_FIRED_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","ENTRY_ID") ;

ALTER TABLE "QRTZ_CRON_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ;

ALTER TABLE "QRTZ_CALENDARS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","CALENDAR_NAME") ;

ALTER TABLE "QRTZ_BLOB_TRIGGERS" ADD CONSTRAINT  PRIMARY KEY("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ;

ALTER TABLE "PORTAL_DATA" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PLUGIN_SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;

ALTER TABLE "PANEL_VIEW_LINKAGE_FIELD" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_VIEW_LINKAGE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_VIEW" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_TEMPLATE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_SUBJECT" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_STORE" ADD CONSTRAINT  PRIMARY KEY("STORE_ID") ;

ALTER TABLE "PANEL_SHARE" ADD CONSTRAINT  PRIMARY KEY("SHARE_ID") ;

ALTER TABLE "PANEL_PDF_TEMPLATE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_OUTER_PARAMS_TARGET_VIEW_INFO" ADD CONSTRAINT  PRIMARY KEY("TARGET_ID") ;

ALTER TABLE "PANEL_OUTER_PARAMS_INFO" ADD CONSTRAINT  PRIMARY KEY("PARAMS_INFO_ID") ;

ALTER TABLE "PANEL_OUTER_PARAMS" ADD CONSTRAINT  PRIMARY KEY("PARAMS_ID") ;

ALTER TABLE "PANEL_LINK_MAPPING" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_LINK_JUMP_TARGET_VIEW_INFO" ADD CONSTRAINT  PRIMARY KEY("TARGET_ID") ;

ALTER TABLE "PANEL_LINK_JUMP_INFO" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_LINK_JUMP" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_GROUP_EXTEND_DATA" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_GROUP_EXTEND" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_GROUP" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "PANEL_DESIGN" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "MY_PLUGIN" ADD CONSTRAINT  PRIMARY KEY("PLUGIN_ID") ;

ALTER TABLE "LICENSE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "FILE_PICTURE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "FILE_METADATA" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "FILE_CONTENT" ADD CONSTRAINT  PRIMARY KEY("FILE_ID") ;

ALTER TABLE "DE_ENGINE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_RECENT_LOCAL_CASES" ADD CONSTRAINT  PRIMARY KEY("CITY") ;

ALTER TABLE "DEMO_OLYMPIAD_MEDAL" ADD CONSTRAINT  PRIMARY KEY("CODE") ;

ALTER TABLE "DEMO_OLYMPIAD_HOT_GAME" ADD CONSTRAINT  PRIMARY KEY("CODE") ;

ALTER TABLE "DEMO_OLYMPIAD_GOLD_DATE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_OLYMPIAD_COUNTRY" ADD CONSTRAINT  PRIMARY KEY("CODE") ;

ALTER TABLE "DEMO_OLYMPIAD_AUDIENCE_SEX" ADD CONSTRAINT  PRIMARY KEY("SEX") ;

ALTER TABLE "DEMO_OLYMPIAD_AUDIENCE_AGE" ADD CONSTRAINT  PRIMARY KEY("AGE") ;

ALTER TABLE "DEMO_OLYMPIAD_ATHLETE" ADD CONSTRAINT  PRIMARY KEY("CODE") ;

ALTER TABLE "DEMO_GDP_HISTORY" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_GDP_DISTRICT_TOP100" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_GDP_BY_INDUSTRY" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_GDP_BY_CITY" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DEMO_GDP_2021" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASOURCE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_UNION" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_TASK_LOG" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_TASK" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_INCREMENTAL_CONFIG" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_FUNCTION" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE_FIELD" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_TABLE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_ROW_PERMISSIONS" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_GROUP" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "DATASET_COLUMN_PERMISSIONS" ADD CONSTRAINT  PRIMARY KEY("ID") ;

-- ALTER TABLE "DATAINS_VERSION" ADD CONSTRAINT  PRIMARY KEY("INSTALLED_RANK") ;

ALTER TABLE "DATAINS_CODE_VERSION" ADD CONSTRAINT  PRIMARY KEY("INSTALLED_RANK") ;

ALTER TABLE "CHART_VIEW_CACHE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "CHART_VIEW" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "CHART_GROUP" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "AREA_MAPPING" ADD CONSTRAINT  PRIMARY KEY("ID") ;

CREATE INDEX "IDX_USER_K_ID"
    ON "USER_KEY"("USER_ID");

CREATE UNIQUE INDEX "PRIMARY"
    ON "USER_KEY"("ID");

COMMENT ON TABLE "USER_KEY" IS '用户KEY';

COMMENT ON COLUMN "USER_KEY"."ID" IS 'ID';

COMMENT ON COLUMN "USER_KEY"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "USER_KEY"."ACCESS_KEY" IS 'access_key';

COMMENT ON COLUMN "USER_KEY"."SECRET_KEY" IS 'secret key';

COMMENT ON COLUMN "USER_KEY"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "USER_KEY"."STATUS" IS '状态';

CREATE UNIQUE INDEX "INDEX92951722731753"
    ON "SYS_USERS_ROLES"("USER_ID","ROLE_ID");

COMMENT ON TABLE "SYS_USERS_ROLES" IS '用户角色关联';

COMMENT ON COLUMN "SYS_USERS_ROLES"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "SYS_USERS_ROLES"."ROLE_ID" IS '角色ID';

CREATE INDEX "FK5RWMRYNY6JTHAAXKOGOWNKNQP"
    ON "SYS_USER"("DEPT_ID");

CREATE INDEX "INX_ENABLED"
    ON "SYS_USER"("ENABLED");

CREATE UNIQUE INDEX "INDEX92951978211980"
    ON "SYS_USER"("USER_ID");

COMMENT ON TABLE "SYS_USER" IS '系统用户';

COMMENT ON COLUMN "SYS_USER"."USER_ID" IS 'ID';

COMMENT ON COLUMN "SYS_USER"."DEPT_ID" IS '部门名称';

COMMENT ON COLUMN "SYS_USER"."USERNAME" IS '用户名';

COMMENT ON COLUMN "SYS_USER"."NICK_NAME" IS '昵称';

COMMENT ON COLUMN "SYS_USER"."GENDER" IS '性别';

COMMENT ON COLUMN "SYS_USER"."PHONE" IS '手机号码';

COMMENT ON COLUMN "SYS_USER"."EMAIL" IS '邮箱';

COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '密码';

COMMENT ON COLUMN "SYS_USER"."IS_ADMIN" IS '是否为admin账号';

COMMENT ON COLUMN "SYS_USER"."ENABLED" IS '状态：1启用、0禁用';

COMMENT ON COLUMN "SYS_USER"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "SYS_USER"."UPDATE_BY" IS '更新着';

COMMENT ON COLUMN "SYS_USER"."PWD_RESET_TIME" IS '修改密码的时间';

COMMENT ON COLUMN "SYS_USER"."CREATE_TIME" IS '创建日期';

COMMENT ON COLUMN "SYS_USER"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "SYS_USER"."LANGUAGE" IS '语言';

COMMENT ON COLUMN "SYS_USER"."FROM" IS '来源';

COMMENT ON COLUMN "SYS_USER"."SUB" IS 'oidc用户ID';

COMMENT ON COLUMN "SYS_THEME_ITEM"."THEME_ID" IS '主题ID';

COMMENT ON COLUMN "SYS_THEME_ITEM"."KEY" IS '样式key';

COMMENT ON COLUMN "SYS_THEME_ITEM"."VAL" IS '样式val';

CREATE UNIQUE INDEX "INDEX92952993547549"
    ON "SYS_THEME"("ID");

COMMENT ON COLUMN "SYS_THEME"."ID" IS '主题id';

COMMENT ON COLUMN "SYS_THEME"."NAME" IS '主题名称';

COMMENT ON COLUMN "SYS_THEME"."IMG_ID" IS '文件ID';

COMMENT ON COLUMN "SYS_THEME"."IMG" IS '主题缩略图';

COMMENT ON COLUMN "SYS_THEME"."STATUS" IS '状态';

CREATE UNIQUE INDEX "INDEX92953321425619"
    ON "SYS_TASK_INSTANCE"("INSTANCE_ID");

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."INSTANCE_ID" IS '任务实例ID';

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."TASK_ID" IS '任务ID';

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."EXECUTE_TIME" IS '执行时间';

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."FINISH_TIME" IS '完成时间';

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."STATUS" IS '实例状态';

COMMENT ON COLUMN "SYS_TASK_INSTANCE"."INFO" IS '执行信息';

CREATE UNIQUE INDEX "INDEX92953739870879"
    ON "SYS_TASK_EMAIL"("ID");

COMMENT ON COLUMN "SYS_TASK_EMAIL"."ID" IS '邮件模版ID';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."TITLE" IS '模版标题';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."PANEL_ID" IS '仪表板ID';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."RECIPIENTS" IS '收件人';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."CONTENT" IS '内容';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."PIXEL" IS '像素';

COMMENT ON COLUMN "SYS_TASK_EMAIL"."TASK_ID" IS '任务ID';

CREATE INDEX "SYS_TASK_TYPE"
    ON "SYS_TASK"("TASK_TYPE");

CREATE UNIQUE INDEX "INDEX92954108320540"
    ON "SYS_TASK"("TASK_ID");

COMMENT ON COLUMN "SYS_TASK"."TASK_ID" IS '任务ID';

COMMENT ON COLUMN "SYS_TASK"."TASK_NAME" IS '任务名称';

COMMENT ON COLUMN "SYS_TASK"."TASK_TYPE" IS '任务类型';

COMMENT ON COLUMN "SYS_TASK"."START_TIME" IS '开始时间';

COMMENT ON COLUMN "SYS_TASK"."END_TIME" IS '结束时间';

COMMENT ON COLUMN "SYS_TASK"."RATE_TYPE" IS '频率方式';

COMMENT ON COLUMN "SYS_TASK"."RATE_VAL" IS '频率值';

COMMENT ON COLUMN "SYS_TASK"."CREATOR" IS '创建者ID';

COMMENT ON COLUMN "SYS_TASK"."CREATE_TIME" IS '创建时间';

CREATE UNIQUE INDEX "INDEX92954429754159"
    ON "SYS_ROLES_MENUS"("MENU_ID","ROLE_ID");

COMMENT ON TABLE "SYS_ROLES_MENUS" IS '角色菜单关联';

COMMENT ON COLUMN "SYS_ROLES_MENUS"."MENU_ID" IS '菜单ID';

COMMENT ON COLUMN "SYS_ROLES_MENUS"."ROLE_ID" IS '角色ID';

CREATE UNIQUE INDEX "INDEX92954572516953"
    ON "SYS_ROLE"("ROLE_ID");

COMMENT ON TABLE "SYS_ROLE" IS '角色表';

COMMENT ON COLUMN "SYS_ROLE"."ROLE_ID" IS 'ID';

COMMENT ON COLUMN "SYS_ROLE"."NAME" IS '名称';

COMMENT ON COLUMN "SYS_ROLE"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "SYS_ROLE"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "SYS_ROLE"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "SYS_ROLE"."CREATE_TIME" IS '创建日期';

COMMENT ON COLUMN "SYS_ROLE"."UPDATE_TIME" IS '更新时间';

CREATE INDEX "INX_MSGTYPE_PID"
    ON "SYS_MSG_TYPE"("PID");

CREATE UNIQUE INDEX "INDEX92954912051032"
    ON "SYS_MSG_TYPE"("MSG_TYPE_ID");

COMMENT ON TABLE "SYS_MSG_TYPE" IS '消息类型表';

COMMENT ON COLUMN "SYS_MSG_TYPE"."MSG_TYPE_ID" IS '主键';

COMMENT ON COLUMN "SYS_MSG_TYPE"."PID" IS '父类ID';

COMMENT ON COLUMN "SYS_MSG_TYPE"."TYPE_NAME" IS '类型名称';

COMMENT ON COLUMN "SYS_MSG_TYPE"."ROUTER" IS '跳转路由';

COMMENT ON COLUMN "SYS_MSG_TYPE"."CALLBACK" IS '回调方法';

CREATE UNIQUE INDEX "INDEX92955185260609"
    ON "SYS_MSG_SETTING"("MSG_SETTING_ID");

COMMENT ON TABLE "SYS_MSG_SETTING" IS '消息设置表';

COMMENT ON COLUMN "SYS_MSG_SETTING"."MSG_SETTING_ID" IS '主键';

COMMENT ON COLUMN "SYS_MSG_SETTING"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "SYS_MSG_SETTING"."TYPE_ID" IS '类型ID';

COMMENT ON COLUMN "SYS_MSG_SETTING"."CHANNEL_ID" IS '渠道ID';

COMMENT ON COLUMN "SYS_MSG_SETTING"."ENABLE" IS '是否启用';

CREATE UNIQUE INDEX "INDEX92955386459010"
    ON "SYS_MSG_CHANNEL"("MSG_CHANNEL_ID");

COMMENT ON TABLE "SYS_MSG_CHANNEL" IS '消息渠道表';

COMMENT ON COLUMN "SYS_MSG_CHANNEL"."MSG_CHANNEL_ID" IS '主键';

COMMENT ON COLUMN "SYS_MSG_CHANNEL"."CHANNEL_NAME" IS '渠道名称';

COMMENT ON COLUMN "SYS_MSG_CHANNEL"."SERVICE_NAME" IS '策略名称';

CREATE INDEX "INX_MSG_STATUS"
    ON "SYS_MSG"("STATUS");

CREATE INDEX "INX_MSG_USERID"
    ON "SYS_MSG"("USER_ID");

CREATE INDEX "INX_MSG_TYPE"
    ON "SYS_MSG"("TYPE_ID");

CREATE UNIQUE INDEX "INDEX92955648758798"
    ON "SYS_MSG"("MSG_ID");

COMMENT ON TABLE "SYS_MSG" IS '消息通知表';

COMMENT ON COLUMN "SYS_MSG"."MSG_ID" IS '消息主键';

COMMENT ON COLUMN "SYS_MSG"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "SYS_MSG"."TYPE_ID" IS '类型';

COMMENT ON COLUMN "SYS_MSG"."STATUS" IS '状态';

COMMENT ON COLUMN "SYS_MSG"."PARAM" IS '路由参数';

COMMENT ON COLUMN "SYS_MSG"."CREATE_TIME" IS '发送时间';

COMMENT ON COLUMN "SYS_MSG"."READ_TIME" IS '读取时间';

COMMENT ON COLUMN "SYS_MSG"."CONTENT" IS '消息内容';

CREATE INDEX "INX_PID"
    ON "SYS_MENU"("PID");

CREATE UNIQUE INDEX "INDEX92956297298930"
    ON "SYS_MENU"("MENU_ID");

COMMENT ON TABLE "SYS_MENU" IS '系统菜单';

COMMENT ON COLUMN "SYS_MENU"."MENU_ID" IS 'ID';

COMMENT ON COLUMN "SYS_MENU"."PID" IS '上级菜单ID';

COMMENT ON COLUMN "SYS_MENU"."SUB_COUNT" IS '子菜单数目';

COMMENT ON COLUMN "SYS_MENU"."TYPE" IS '菜单类型';

COMMENT ON COLUMN "SYS_MENU"."TITLE" IS '菜单标题';

COMMENT ON COLUMN "SYS_MENU"."NAME" IS '组件名称';

COMMENT ON COLUMN "SYS_MENU"."COMPONENT" IS '组件';

COMMENT ON COLUMN "SYS_MENU"."MENU_SORT" IS '排序';

COMMENT ON COLUMN "SYS_MENU"."ICON" IS '图标';

COMMENT ON COLUMN "SYS_MENU"."PATH" IS '链接地址';

COMMENT ON COLUMN "SYS_MENU"."I_FRAME" IS '是否外链';

COMMENT ON COLUMN "SYS_MENU"."CACHE" IS '缓存';

COMMENT ON COLUMN "SYS_MENU"."HIDDEN" IS '隐藏';

COMMENT ON COLUMN "SYS_MENU"."PERMISSION" IS '权限';

COMMENT ON COLUMN "SYS_MENU"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "SYS_MENU"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "SYS_MENU"."CREATE_TIME" IS '创建日期';

COMMENT ON COLUMN "SYS_MENU"."UPDATE_TIME" IS '更新时间';

CREATE INDEX "INDEX92956963448856"
    ON "SYS_DEPT"("PID");

CREATE UNIQUE INDEX "INDEX92957007250673"
    ON "SYS_DEPT"("DEPT_ID");

COMMENT ON TABLE "SYS_DEPT" IS '组织机构';

COMMENT ON COLUMN "SYS_DEPT"."DEPT_ID" IS 'ID';

COMMENT ON COLUMN "SYS_DEPT"."PID" IS '上级部门';

COMMENT ON COLUMN "SYS_DEPT"."SUB_COUNT" IS '子部门数目';

COMMENT ON COLUMN "SYS_DEPT"."NAME" IS '名称';

COMMENT ON COLUMN "SYS_DEPT"."DEPT_SORT" IS '排序';

COMMENT ON COLUMN "SYS_DEPT"."CREATE_BY" IS '创建者';

COMMENT ON COLUMN "SYS_DEPT"."UPDATE_BY" IS '更新者';

COMMENT ON COLUMN "SYS_DEPT"."CREATE_TIME" IS '创建日期';

COMMENT ON COLUMN "SYS_DEPT"."UPDATE_TIME" IS '更新时间';

CREATE UNIQUE INDEX "INDEX92957311587832"
    ON "SYS_BACKGROUND_IMAGE"("ID");

CREATE UNIQUE INDEX "INDEX92957345476307"
    ON "SYS_AUTH_DETAIL"("ID");

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."PRIVILEGE_NAME" IS '权限名称';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."PRIVILEGE_TYPE" IS '权限类型';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."PRIVILEGE_VALUE" IS '权限值 1 可用 2 不用';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."PRIVILEGE_EXTEND" IS '权限扩展';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."REMARK" IS '备注';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."COPY_FROM" IS '复制来源';

COMMENT ON COLUMN "SYS_AUTH_DETAIL"."COPY_ID" IS '复制ID';

CREATE UNIQUE INDEX "INDEX92957854469203"
    ON "SYS_AUTH"("ID");

COMMENT ON COLUMN "SYS_AUTH"."AUTH_SOURCE" IS '授权资产源 数据集 视图 仪表板';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_SOURCE_TYPE" IS '授权资产类型 dataset 数据集 view 视图 panel 仪表板';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_TARGET" IS '授权目标 用户 角色 组织 ';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_TARGET_TYPE" IS '授权目标类型 user 用户 role 角色 org dept 组织';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_TIME" IS '授权时间';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_DETAILS" IS '授权明细 privilegename 名称 privilegeType 权限类型 1 查看 2 管理 3 导出 4 使用 ; privilegeValue 1 不可用 2 可用 3 部分可用';

COMMENT ON COLUMN "SYS_AUTH"."AUTH_USER" IS '授权人员';

COMMENT ON COLUMN "SYS_AUTH"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "SYS_AUTH"."COPY_FROM" IS '复制来源';

COMMENT ON COLUMN "SYS_AUTH"."COPY_ID" IS '复制ID';

CREATE UNIQUE INDEX "INDEX92951555408938"
    ON "SYSTEM_PARAMETER"("PARAM_KEY");

COMMENT ON COLUMN "SYSTEM_PARAMETER"."PARAM_KEY" IS 'Parameter name';

COMMENT ON COLUMN "SYSTEM_PARAMETER"."PARAM_VALUE" IS 'Parameter value';

COMMENT ON COLUMN "SYSTEM_PARAMETER"."TYPE" IS 'Parameter type';

COMMENT ON COLUMN "SYSTEM_PARAMETER"."SORT" IS 'Sort';

CREATE INDEX "RESOURCE_ID"
    ON "SCHEDULE"("RESOURCE_ID");

CREATE UNIQUE INDEX "INDEX92958294513595"
    ON "SCHEDULE"("ID");

COMMENT ON COLUMN "SCHEDULE"."ID" IS 'Schedule ID';

COMMENT ON COLUMN "SCHEDULE"."KEY" IS 'Schedule Key';

COMMENT ON COLUMN "SCHEDULE"."TYPE" IS 'Schedule Type';

COMMENT ON COLUMN "SCHEDULE"."VALUE" IS 'Schedule value';

COMMENT ON COLUMN "SCHEDULE"."GROUP" IS 'Group Name';

COMMENT ON COLUMN "SCHEDULE"."JOB" IS 'Schedule Job Class Name';

COMMENT ON COLUMN "SCHEDULE"."ENABLE" IS 'Schedule Eable';

COMMENT ON COLUMN "SCHEDULE"."RESOURCE_ID" IS 'Resource Id';

COMMENT ON COLUMN "SCHEDULE"."USER_ID" IS 'Change User';

COMMENT ON COLUMN "SCHEDULE"."CUSTOM_DATA" IS 'Custom Data (JSON format)';

CREATE INDEX "IDX_QRTZ_T_STATE"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_STATE");

CREATE INDEX "IDX_QRTZ_T_JG"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","JOB_GROUP");

CREATE INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME","TRIGGER_STATE");

CREATE INDEX "IDX_QRTZ_T_C"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","CALENDAR_NAME");

CREATE INDEX "IDX_QRTZ_T_G"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_GROUP");

CREATE INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","NEXT_FIRE_TIME");

CREATE INDEX "IDX_QRTZ_T_J"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","JOB_NAME","JOB_GROUP");

CREATE INDEX "IDX_QRTZ_T_NFT_MISFIRE"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME");

CREATE INDEX "IDX_QRTZ_T_N_STATE"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP","TRIGGER_STATE");

CREATE INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","MISFIRE_INSTR","NEXT_FIRE_TIME","TRIGGER_GROUP","TRIGGER_STATE");

CREATE INDEX "IDX_QRTZ_T_N_G_STATE"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_GROUP","TRIGGER_STATE");

CREATE INDEX "IDX_QRTZ_T_NFT_ST"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_STATE","NEXT_FIRE_TIME");

CREATE UNIQUE INDEX "INDEX92959448792843"
    ON "QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92959505672449"
    ON "QRTZ_SIMPROP_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92959572796064"
    ON "QRTZ_SIMPLE_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92959755597560"
    ON "QRTZ_SCHEDULER_STATE"("SCHED_NAME","INSTANCE_NAME");

CREATE UNIQUE INDEX "INDEX92959789393146"
    ON "QRTZ_PAUSED_TRIGGER_GRPS"("SCHED_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92959840943414"
    ON "QRTZ_LOCKS"("SCHED_NAME","LOCK_NAME");

CREATE INDEX "IDX_QRTZ_J_REQ_RECOVERY"
    ON "QRTZ_JOB_DETAILS"("SCHED_NAME","REQUESTS_RECOVERY");

CREATE INDEX "IDX_QRTZ_J_GRP"
    ON "QRTZ_JOB_DETAILS"("SCHED_NAME","JOB_GROUP");

CREATE UNIQUE INDEX "INDEX92960001062667"
    ON "QRTZ_JOB_DETAILS"("SCHED_NAME","JOB_NAME","JOB_GROUP");

CREATE INDEX "IDX_QRTZ_FT_INST_JOB_REQ_RCVRY"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","INSTANCE_NAME","REQUESTS_RECOVERY");

CREATE INDEX "IDX_QRTZ_FT_J_G"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","JOB_NAME","JOB_GROUP");

CREATE INDEX "IDX_QRTZ_FT_TG"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","TRIGGER_GROUP");

CREATE INDEX "IDX_QRTZ_FT_T_G"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE INDEX "IDX_QRTZ_FT_TRIG_INST_NAME"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","INSTANCE_NAME");

CREATE INDEX "IDX_QRTZ_FT_JG"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","JOB_GROUP");

CREATE UNIQUE INDEX "INDEX92960306535383"
    ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME","ENTRY_ID");

CREATE UNIQUE INDEX "INDEX92960351098534"
    ON "QRTZ_CRON_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92960381561672"
    ON "QRTZ_CALENDARS"("SCHED_NAME","CALENDAR_NAME");

CREATE INDEX "SCHED_NAME"
    ON "QRTZ_BLOB_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92960564273390"
    ON "QRTZ_BLOB_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP");

CREATE UNIQUE INDEX "INDEX92960607203206"
    ON "PORTAL_DATA"("ID");

COMMENT ON TABLE "PORTAL_DATA" IS '数据门户';

COMMENT ON COLUMN "PORTAL_DATA"."USER_ID" IS '创建人id';

COMMENT ON COLUMN "PORTAL_DATA"."USER_NAME" IS '创建人名称';

COMMENT ON COLUMN "PORTAL_DATA"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "PORTAL_DATA"."UPDATE_TIME" IS '修改时间';

COMMENT ON COLUMN "PORTAL_DATA"."CREATE_TIME" IS '创建时间';

CREATE UNIQUE INDEX "INDEX92960873398554"
    ON "PLUGIN_SYS_MENU"("MENU_ID");

CREATE UNIQUE INDEX "INDEX92960907049250"
    ON "PANEL_VIEW_LINKAGE_FIELD"("ID");

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE_FIELD"."LINKAGE_ID" IS '联动ID';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE_FIELD"."SOURCE_FIELD" IS '源视图字段';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE_FIELD"."TARGET_FIELD" IS '目标视图字段';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE_FIELD"."UPDATE_TIME" IS '更新时间';

CREATE UNIQUE INDEX "INDEX92961124633888"
    ON "PANEL_VIEW_LINKAGE"("ID");

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE"."SOURCE_VIEW_ID" IS '源视图id';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE"."TARGET_VIEW_ID" IS '联动视图id';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "PANEL_VIEW_LINKAGE"."UPDATE_PEOPLE" IS '更新人';

CREATE UNIQUE INDEX "INDEX92961276386467"
    ON "PANEL_VIEW"("ID");

COMMENT ON COLUMN "PANEL_VIEW"."PANEL_ID" IS 'panel_id';

COMMENT ON COLUMN "PANEL_VIEW"."CHART_VIEW_ID" IS 'chart_view_id';

COMMENT ON COLUMN "PANEL_VIEW"."CONTENT" IS '内容';

COMMENT ON COLUMN "PANEL_VIEW"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "PANEL_VIEW"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "PANEL_VIEW"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "PANEL_VIEW"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "PANEL_VIEW"."POSITION" IS '视图位置 panel 仪表板中，tab Tab页中';

COMMENT ON COLUMN "PANEL_VIEW"."COPY_FROM" IS '如果有复制 最近一次的复制来源id';

COMMENT ON COLUMN "PANEL_VIEW"."COPY_ID" IS '本次复制的执行ID';

CREATE UNIQUE INDEX "INDEX92962048933376"
    ON "PANEL_TEMPLATE"("ID");

COMMENT ON COLUMN "PANEL_TEMPLATE"."NAME" IS '名称';

COMMENT ON COLUMN "PANEL_TEMPLATE"."PID" IS '父级id';

COMMENT ON COLUMN "PANEL_TEMPLATE"."LEVEL" IS '层级';

COMMENT ON COLUMN "PANEL_TEMPLATE"."NODE_TYPE" IS '节点类型  folder or panel 目录或者文件夹';

COMMENT ON COLUMN "PANEL_TEMPLATE"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "PANEL_TEMPLATE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "PANEL_TEMPLATE"."SNAPSHOT" IS '缩略图';

COMMENT ON COLUMN "PANEL_TEMPLATE"."TEMPLATE_TYPE" IS '仪表板类型 system 系统内置 self 用户自建 ';

COMMENT ON COLUMN "PANEL_TEMPLATE"."TEMPLATE_STYLE" IS 'template 样式';

COMMENT ON COLUMN "PANEL_TEMPLATE"."TEMPLATE_DATA" IS 'template 数据';

COMMENT ON COLUMN "PANEL_TEMPLATE"."DYNAMIC_DATA" IS '预存数据';

CREATE UNIQUE INDEX "INDEX92962549563155"
    ON "PANEL_SUBJECT"("ID");

COMMENT ON COLUMN "PANEL_SUBJECT"."NAME" IS '主题名称';

COMMENT ON COLUMN "PANEL_SUBJECT"."TYPE" IS '主题类型 system 系统主题，self 自定义主题';

COMMENT ON COLUMN "PANEL_SUBJECT"."DETAILS" IS '主题内容';

COMMENT ON COLUMN "PANEL_SUBJECT"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "PANEL_SUBJECT"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "PANEL_SUBJECT"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "PANEL_SUBJECT"."UPDATE_BY" IS '更新人';

CREATE UNIQUE INDEX "INDEX92962791178925"
    ON "PANEL_STORE"("STORE_ID");

COMMENT ON TABLE "PANEL_STORE" IS '仪表板收藏';

COMMENT ON COLUMN "PANEL_STORE"."STORE_ID" IS 'ID';

COMMENT ON COLUMN "PANEL_STORE"."PANEL_GROUP_ID" IS '仪表板ID';

COMMENT ON COLUMN "PANEL_STORE"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "PANEL_STORE"."CREATE_TIME" IS '创建日期';

CREATE UNIQUE INDEX "INDEX92963016971126"
    ON "PANEL_SHARE"("SHARE_ID");

COMMENT ON TABLE "PANEL_SHARE" IS '仪表板分享';

COMMENT ON COLUMN "PANEL_SHARE"."SHARE_ID" IS '分享ID';

COMMENT ON COLUMN "PANEL_SHARE"."PANEL_GROUP_ID" IS '仪表板ID';

COMMENT ON COLUMN "PANEL_SHARE"."TARGET_ID" IS '目标ID';

COMMENT ON COLUMN "PANEL_SHARE"."GRANTER" IS '分享人';

COMMENT ON COLUMN "PANEL_SHARE"."CREATE_TIME" IS '创建日期';

COMMENT ON COLUMN "PANEL_SHARE"."TYPE" IS '类型0:user,1:role,2dept';

CREATE UNIQUE INDEX "INDEX92963292632704"
    ON "PANEL_PDF_TEMPLATE"("ID");

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."ID" IS 'id';

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."NAME" IS '模板名称';

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."CREATE_USER" IS '创建人';

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."TEMPLATE_CONTENT" IS '模板内容';

COMMENT ON COLUMN "PANEL_PDF_TEMPLATE"."SORT" IS '排序';

CREATE UNIQUE INDEX "INDEX92963483261762"
    ON "PANEL_OUTER_PARAMS_TARGET_VIEW_INFO"("TARGET_ID");

CREATE UNIQUE INDEX "INDEX92963532409362"
    ON "PANEL_OUTER_PARAMS_INFO"("PARAMS_INFO_ID");

COMMENT ON COLUMN "PANEL_OUTER_PARAMS_INFO"."PARAM_NAME" IS '参数名';

COMMENT ON COLUMN "PANEL_OUTER_PARAMS_INFO"."CHECKED" IS '是否启用';

CREATE UNIQUE INDEX "INDEX92963665305480"
    ON "PANEL_OUTER_PARAMS"("PARAMS_ID");

CREATE UNIQUE INDEX "INDEX92963702866846"
    ON "PANEL_LINK_MAPPING"("ID");

COMMENT ON COLUMN "PANEL_LINK_MAPPING"."ID" IS 'id';

COMMENT ON COLUMN "PANEL_LINK_MAPPING"."RESOURCE_ID" IS '仪表板ID';

COMMENT ON COLUMN "PANEL_LINK_MAPPING"."UUID" IS 'uuid';

CREATE UNIQUE INDEX "INDEX92963943276394"
    ON "PANEL_LINK_JUMP_TARGET_VIEW_INFO"("TARGET_ID");

CREATE UNIQUE INDEX "INDEX92963975286644"
    ON "PANEL_LINK_JUMP_INFO"("ID");

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."LINK_JUMP_ID" IS 'link jump ID';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."LINK_TYPE" IS '关联类型 inner 内部仪表板，outer 外部链接';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."JUMP_TYPE" IS '跳转类型 _blank 新开页面 _self 当前窗口';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."TARGET_PANEL_ID" IS '关联仪表板ID';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."SOURCE_FIELD_ID" IS '字段ID';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."CONTENT" IS '内容 linkType = outer时使用';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."CHECKED" IS '是否可用';

COMMENT ON COLUMN "PANEL_LINK_JUMP_INFO"."ATTACH_PARAMS" IS '是否附加点击参数';

CREATE UNIQUE INDEX "INDEX92964186046387"
    ON "PANEL_LINK_JUMP"("ID");

COMMENT ON COLUMN "PANEL_LINK_JUMP"."SOURCE_PANEL_ID" IS '源仪表板ID';

COMMENT ON COLUMN "PANEL_LINK_JUMP"."SOURCE_VIEW_ID" IS '源视图ID';

COMMENT ON COLUMN "PANEL_LINK_JUMP"."LINK_JUMP_INFO" IS '跳转信息';

COMMENT ON COLUMN "PANEL_LINK_JUMP"."CHECKED" IS '是否启用';

COMMENT ON TABLE "PANEL_LINK" IS '仪表板链接';

COMMENT ON COLUMN "PANEL_LINK"."RESOURCE_ID" IS '资源ID';

COMMENT ON COLUMN "PANEL_LINK"."VALID" IS '启用链接';

COMMENT ON COLUMN "PANEL_LINK"."ENABLE_PWD" IS '启用密码';

COMMENT ON COLUMN "PANEL_LINK"."PWD" IS '密码';

COMMENT ON COLUMN "PANEL_LINK"."OVER_TIME" IS '有效截止时间';

CREATE UNIQUE INDEX "INDEX92964325278511"
    ON "PANEL_GROUP_EXTEND_DATA"("ID");

CREATE UNIQUE INDEX "INDEX92964367309659"
    ON "PANEL_GROUP_EXTEND"("ID");

COMMENT ON COLUMN "PANEL_GROUP_EXTEND"."TEMPLATE_ID" IS '模板来源id';

COMMENT ON COLUMN "PANEL_GROUP_EXTEND"."TEMPLATE_DYNAMIC_DATA" IS '模板动态数据';

COMMENT ON COLUMN "PANEL_GROUP_EXTEND"."TEMPLATE_VERSION" IS '模板版本号(预留)';

CREATE UNIQUE INDEX "INDEX92964502050668"
    ON "PANEL_GROUP"("ID");

COMMENT ON COLUMN "PANEL_GROUP"."NAME" IS '名称';

COMMENT ON COLUMN "PANEL_GROUP"."PID" IS '父级id';

COMMENT ON COLUMN "PANEL_GROUP"."LEVEL" IS '层级';

COMMENT ON COLUMN "PANEL_GROUP"."NODE_TYPE" IS '节点类型  folder or panel 目录或者文件夹';

COMMENT ON COLUMN "PANEL_GROUP"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "PANEL_GROUP"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "PANEL_GROUP"."PANEL_TYPE" IS '仪表板类型 system 系统内置 self 用户自建 ';

COMMENT ON COLUMN "PANEL_GROUP"."PANEL_STYLE" IS 'panel 样式';

COMMENT ON COLUMN "PANEL_GROUP"."PANEL_DATA" IS 'panel 数据';

COMMENT ON COLUMN "PANEL_GROUP"."SOURCE" IS '数据来源 导入 或者 其他仪表板另存';

COMMENT ON COLUMN "PANEL_GROUP"."MOBILE_LAYOUT" IS '启用移动端布局';

CREATE UNIQUE INDEX "INDEX92964968363971"
    ON "PANEL_DESIGN"("ID");

COMMENT ON TABLE "PANEL_DESIGN" IS '仪表板和组件的关联关系 组件分为普通视图和系统组件';

COMMENT ON COLUMN "PANEL_DESIGN"."PANEL_ID" IS 'panel id';

COMMENT ON COLUMN "PANEL_DESIGN"."COMPONENT_ID" IS '组件 id';

COMMENT ON COLUMN "PANEL_DESIGN"."COMPONENT_STYLE" IS '组件样式 样式';

COMMENT ON COLUMN "PANEL_DESIGN"."COMPONENT_POSITION" IS '组件样式 样式定位';

COMMENT ON COLUMN "PANEL_DESIGN"."COMPONENT_TYPE" IS '组件 类型 view 视图 public 公共组件';

COMMENT ON COLUMN "PANEL_DESIGN"."COMPONENT_DETAILS" IS '组件明细';

COMMENT ON COLUMN "PANEL_DESIGN"."UPDATE_TIME" IS '修改时间';

COMMENT ON COLUMN "PANEL_DESIGN"."UPDATE_PERSON" IS '修改人';

CREATE UNIQUE INDEX "INDEX92965375454111"
    ON "MY_PLUGIN"("PLUGIN_ID");

COMMENT ON TABLE "MY_PLUGIN" IS '插件表';

COMMENT ON COLUMN "MY_PLUGIN"."PLUGIN_ID" IS '主键';

COMMENT ON COLUMN "MY_PLUGIN"."NAME" IS '插件名称';

COMMENT ON COLUMN "MY_PLUGIN"."STORE" IS '商家';

COMMENT ON COLUMN "MY_PLUGIN"."FREE" IS '是否免费';

COMMENT ON COLUMN "MY_PLUGIN"."COST" IS '费用';

COMMENT ON COLUMN "MY_PLUGIN"."CATEGORY" IS '列别';

COMMENT ON COLUMN "MY_PLUGIN"."DESCRIPT" IS '描述';

COMMENT ON COLUMN "MY_PLUGIN"."VERSION" IS '版本号';

COMMENT ON COLUMN "MY_PLUGIN"."INSTALL_TYPE" IS '安装类型';

COMMENT ON COLUMN "MY_PLUGIN"."CREATOR" IS '开发者';

COMMENT ON COLUMN "MY_PLUGIN"."LOAD_MYBATIS" IS '是否需要加载mybatis';

COMMENT ON COLUMN "MY_PLUGIN"."RELEASE_TIME" IS '发布时间';

COMMENT ON COLUMN "MY_PLUGIN"."INSTALL_TIME" IS '安装时间';

COMMENT ON COLUMN "MY_PLUGIN"."MODULE_NAME" IS 'jar包名称';

COMMENT ON COLUMN "MY_PLUGIN"."ICON" IS '图标';

CREATE UNIQUE INDEX "INDEX92966044104483"
    ON "LICENSE"("ID");

COMMENT ON COLUMN "LICENSE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "LICENSE"."LICENSE" IS 'license';

COMMENT ON COLUMN "LICENSE"."F2C_LICENSE" IS 'F2C License';

CREATE UNIQUE INDEX "INDEX92966371176774"
    ON "FILE_PICTURE"("ID");

COMMENT ON TABLE "FILE_PICTURE" IS '图片表';

COMMENT ON COLUMN "FILE_PICTURE"."URL" IS '图片地址';

COMMENT ON COLUMN "FILE_PICTURE"."IMG_DETAILED" IS '图片详细信息';

COMMENT ON COLUMN "FILE_PICTURE"."TYPE" IS '图片类型';

COMMENT ON COLUMN "FILE_PICTURE"."NAME" IS '文件分类名';

CREATE UNIQUE INDEX "INDEX92966635288120"
    ON "FILE_METADATA"("ID");

COMMENT ON COLUMN "FILE_METADATA"."ID" IS 'File ID';

COMMENT ON COLUMN "FILE_METADATA"."NAME" IS 'File name';

COMMENT ON COLUMN "FILE_METADATA"."TYPE" IS 'File type';

COMMENT ON COLUMN "FILE_METADATA"."SIZE" IS 'File size';

COMMENT ON COLUMN "FILE_METADATA"."CREATE_TIME" IS 'Create timestamp';

COMMENT ON COLUMN "FILE_METADATA"."UPDATE_TIME" IS 'Update timestamp';

CREATE UNIQUE INDEX "INDEX92966844086083"
    ON "FILE_CONTENT"("FILE_ID");

COMMENT ON COLUMN "FILE_CONTENT"."FILE_ID" IS 'File ID';

COMMENT ON COLUMN "FILE_CONTENT"."FILE" IS 'File content';

CREATE UNIQUE INDEX "INDEX92968636200565"
    ON "DE_ENGINE"("ID");

COMMENT ON COLUMN "DE_ENGINE"."ID" IS 'ID';

COMMENT ON COLUMN "DE_ENGINE"."NAME" IS '名称';

COMMENT ON COLUMN "DE_ENGINE"."DESC" IS '描述';

COMMENT ON COLUMN "DE_ENGINE"."TYPE" IS '类型';

COMMENT ON COLUMN "DE_ENGINE"."CONFIGURATION" IS '详细信息';

COMMENT ON COLUMN "DE_ENGINE"."CREATE_TIME" IS 'Create timestamp';

COMMENT ON COLUMN "DE_ENGINE"."UPDATE_TIME" IS 'Update timestamp';

COMMENT ON COLUMN "DE_ENGINE"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "DE_ENGINE"."STATUS" IS '状态';

COMMENT ON COLUMN "DEMO_VACCINATION"."CUMULATIVE" IS '累计接种';

COMMENT ON COLUMN "DEMO_VACCINATION"."NEW_ADD" IS '较上日新增';

COMMENT ON COLUMN "DEMO_VACCINATION"."VACCINATION_PER_100_PEOPLE" IS '每百人接种';

ALTER TABLE "DEMO_SALES_DASHBOARD" ADD CHECK ("YEAR" >= 0) ENABLE ;

CREATE UNIQUE INDEX "INDEX92967129280114"
    ON "DEMO_RECENT_LOCAL_CASES"("CITY");

COMMENT ON COLUMN "DEMO_RECENT_LOCAL_CASES"."CITY" IS '城市';

COMMENT ON COLUMN "DEMO_RECENT_LOCAL_CASES"."PROVINCE" IS '省市区';

COMMENT ON COLUMN "DEMO_RECENT_LOCAL_CASES"."NEW_ADD" IS '新增';

COMMENT ON COLUMN "DEMO_RECENT_LOCAL_CASES"."EXISTING" IS '现有';

COMMENT ON COLUMN "DEMO_RECENT_LOCAL_CASES"."RISK" IS '区域风险';

CREATE UNIQUE INDEX "INDEX92967368972772"
    ON "DEMO_OLYMPIAD_MEDAL"("CODE");

CREATE UNIQUE INDEX "INDEX92967418926594"
    ON "DEMO_OLYMPIAD_HOT_GAME"("CODE");

CREATE UNIQUE INDEX "INDEX92967585932076"
    ON "DEMO_OLYMPIAD_GOLD_DATE"("ID");

CREATE UNIQUE INDEX "INDEX92967629574337"
    ON "DEMO_OLYMPIAD_COUNTRY"("CODE");

CREATE UNIQUE INDEX "INDEX92967680193937"
    ON "DEMO_OLYMPIAD_AUDIENCE_SEX"("SEX");

CREATE UNIQUE INDEX "INDEX92967719117528"
    ON "DEMO_OLYMPIAD_AUDIENCE_AGE"("AGE");

CREATE UNIQUE INDEX "INDEX92967807547384"
    ON "DEMO_OLYMPIAD_ATHLETE"("CODE");

COMMENT ON COLUMN "DEMO_NEW_TREND_OF_DIAGNOSIS"."DATE" IS '日期';

COMMENT ON COLUMN "DEMO_NEW_TREND_OF_DIAGNOSIS"."NEW_DIAGNOSIS" IS '新增确诊';

COMMENT ON COLUMN "DEMO_NEW_TREND_OF_DIAGNOSIS"."CURRENT_DIAGNOSIS" IS '现有确诊';

CREATE UNIQUE INDEX "INDEX92967927279490"
    ON "DEMO_GDP_HISTORY"("ID");

CREATE UNIQUE INDEX "INDEX92967963909301"
    ON "DEMO_GDP_DISTRICT_TOP100"("ID");

CREATE UNIQUE INDEX "INDEX92968002338668"
    ON "DEMO_GDP_BY_INDUSTRY"("ID");

CREATE UNIQUE INDEX "INDEX92968312612722"
    ON "DEMO_GDP_BY_CITY"("ID");

CREATE UNIQUE INDEX "INDEX92968336531410"
    ON "DEMO_GDP_2021"("ID");

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."STATISTICAL_TIME" IS '统计时间';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."CUMULATIVE_CURE" IS '累计治愈';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."CURRENT_DIAGNOSIS" IS '现有确诊';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."CUMULATIVE_DIAGNOSIS" IS '累计确诊';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."ASYMPTOMATIC_PATIENT" IS '无症状感染者';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."INPUT" IS '境外输入';

COMMENT ON COLUMN "DEMO_DOMESTIC_EPIDEMIC"."CUMULATIVE_DEATH" IS '累计死亡';

CREATE UNIQUE INDEX "INDEX92969107615651"
    ON "DATASOURCE"("ID");

COMMENT ON COLUMN "DATASOURCE"."ID" IS 'ID';

COMMENT ON COLUMN "DATASOURCE"."NAME" IS '名称';

COMMENT ON COLUMN "DATASOURCE"."DESC" IS '描述';

COMMENT ON COLUMN "DATASOURCE"."TYPE" IS '类型';

COMMENT ON COLUMN "DATASOURCE"."CONFIGURATION" IS '详细信息';

COMMENT ON COLUMN "DATASOURCE"."CREATE_TIME" IS 'Create timestamp';

COMMENT ON COLUMN "DATASOURCE"."UPDATE_TIME" IS 'Update timestamp';

COMMENT ON COLUMN "DATASOURCE"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "DATASOURCE"."STATUS" IS '状态';

CREATE UNIQUE INDEX "INDEX92969688514389"
    ON "DATASET_TABLE_UNION"("ID");

COMMENT ON COLUMN "DATASET_TABLE_UNION"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."SOURCE_TABLE_ID" IS '关联表ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."SOURCE_TABLE_FIELD_ID" IS '关联字段ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."SOURCE_UNION_RELATION" IS '关联关系,1:1、1:N、N:1';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."TARGET_TABLE_ID" IS '被关联表ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."TARGET_TABLE_FIELD_ID" IS '被关联字段ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."TARGET_UNION_RELATION" IS '被关联关系,1:1、1:N、N:1';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "DATASET_TABLE_UNION"."CREATE_TIME" IS '创建时间';

CREATE INDEX "IDX_DATASET_TABLE_TASK_LOG_TASK_ID"
    ON "DATASET_TABLE_TASK_LOG"("TASK_ID");

CREATE INDEX "IDX_DATASET_TABLE_TASK_LOG_TABLE_ID"
    ON "DATASET_TABLE_TASK_LOG"("TABLE_ID");

CREATE UNIQUE INDEX "INDEX92970108210762"
    ON "DATASET_TABLE_TASK_LOG"("ID");

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."TABLE_ID" IS '表ID';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."TASK_ID" IS '任务ID';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."START_TIME" IS '开始时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."END_TIME" IS '结束时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."STATUS" IS '执行状态';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."INFO" IS '错误信息';

COMMENT ON COLUMN "DATASET_TABLE_TASK_LOG"."CREATE_TIME" IS '创建时间';

CREATE INDEX "IDX_DATASET_TABLE_TASK_TABLE_ID"
    ON "DATASET_TABLE_TASK"("TABLE_ID");

CREATE INDEX "IDX_DATASET_TABLE_TASK_NAME"
    ON "DATASET_TABLE_TASK"("NAME");

CREATE UNIQUE INDEX "INDEX92970648962799"
    ON "DATASET_TABLE_TASK"("ID");

COMMENT ON COLUMN "DATASET_TABLE_TASK"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."TABLE_ID" IS '表ID';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."NAME" IS '任务名称';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."TYPE" IS '更新方式：0-全量更新 1-增量更新';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."START_TIME" IS '开始时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."RATE" IS '执行频率：0 一次性 1 cron';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."CRON" IS 'cron表达式';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."END" IS '结束限制 0 无限制 1 设定结束时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."END_TIME" IS '结束时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."LAST_EXEC_TIME" IS '上次执行时间';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."LAST_EXEC_STATUS" IS '上次执行结果';

COMMENT ON COLUMN "DATASET_TABLE_TASK"."STATUS" IS '任务状态';

CREATE UNIQUE INDEX "INDEX92971229911759"
    ON "DATASET_TABLE_INCREMENTAL_CONFIG"("ID");

COMMENT ON COLUMN "DATASET_TABLE_INCREMENTAL_CONFIG"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_INCREMENTAL_CONFIG"."TABLE_ID" IS '表ID';

COMMENT ON COLUMN "DATASET_TABLE_INCREMENTAL_CONFIG"."INCREMENTAL_DELETE" IS '详细信息';

COMMENT ON COLUMN "DATASET_TABLE_INCREMENTAL_CONFIG"."INCREMENTAL_ADD" IS '详细信息';

CREATE UNIQUE INDEX "INDEX92971403658581"
    ON "DATASET_TABLE_FUNCTION"("ID");

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."NAME" IS '函数名称';

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."FUNC" IS '函数表达式';

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."DB_TYPE" IS '所属数据库';

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."FUNC_TYPE" IS '函数类型：0-聚合函数；1-快速计算函数；2-数学和三角函数；3-日期函数；4-文本函数；5-逻辑函数；6-其它函数';

COMMENT ON COLUMN "DATASET_TABLE_FUNCTION"."DESC" IS '描述';

CREATE UNIQUE INDEX "INDEX92971762975344"
    ON "DATASET_TABLE_FIELD"("ID");

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."TABLE_ID" IS '表ID';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."NAME" IS '字段名';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."DATAINS_NAME" IS '字段名';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."GROUP_TYPE" IS '维度/指标标识 d:维度，q:指标';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."TYPE" IS '原始字段类型';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."DE_TYPE" IS 'datains字段类型：0-文本，1-时间，2-整型数值，3-浮点数值...';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."DE_TYPE_FORMAT" IS '类型格式';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."EXT_FIELD" IS '是否扩展字段 0否 1是';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."CHECKED" IS '是否选中';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."COLUMN_INDEX" IS '列位置';

COMMENT ON COLUMN "DATASET_TABLE_FIELD"."LAST_SYNC_TIME" IS '同步时间';

CREATE UNIQUE INDEX "INDEX92972390674569"
    ON "DATASET_TABLE"("ID");

COMMENT ON COLUMN "DATASET_TABLE"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_TABLE"."SCENE_ID" IS '场景ID';

COMMENT ON COLUMN "DATASET_TABLE"."DATA_SOURCE_ID" IS '数据源ID';

COMMENT ON COLUMN "DATASET_TABLE"."TYPE" IS 'db,sql,excel,custom';

COMMENT ON COLUMN "DATASET_TABLE"."MODE" IS '连接模式：0-直连，1-定时同步';

COMMENT ON COLUMN "DATASET_TABLE"."INFO" IS '表原始信息';

COMMENT ON COLUMN "DATASET_TABLE"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "DATASET_TABLE"."CREATE_TIME" IS '创建时间';

CREATE UNIQUE INDEX "INDEX92972871387885"
    ON "DATASET_ROW_PERMISSIONS"("ID");

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."ID" IS 'File ID';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."AUTH_TARGET_TYPE" IS '权限类型：组织/角色/用户';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."AUTH_TARGET_ID" IS '权限对象ID';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."DATASET_ID" IS '数据集ID';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."DATASET_FIELD_ID" IS '数据集字段ID';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."FILTER_TYPE" IS '过滤类型:逻辑、枚举';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."LOGIC" IS '与/或';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."FILTER" IS '数值';

COMMENT ON COLUMN "DATASET_ROW_PERMISSIONS"."ENUM_CHECK_FIELD" IS '枚举值';

CREATE UNIQUE INDEX "INDEX92973416644814"
    ON "DATASET_GROUP"("ID");

COMMENT ON COLUMN "DATASET_GROUP"."ID" IS 'ID';

COMMENT ON COLUMN "DATASET_GROUP"."NAME" IS '名称';

COMMENT ON COLUMN "DATASET_GROUP"."PID" IS '父级ID';

COMMENT ON COLUMN "DATASET_GROUP"."LEVEL" IS '当前分组处于第几级';

COMMENT ON COLUMN "DATASET_GROUP"."TYPE" IS 'group or scene';

COMMENT ON COLUMN "DATASET_GROUP"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "DATASET_GROUP"."CREATE_TIME" IS '创建时间';

CREATE UNIQUE INDEX "INDEX92973754533115"
    ON "DATASET_COLUMN_PERMISSIONS"("ID");

COMMENT ON COLUMN "DATASET_COLUMN_PERMISSIONS"."ID" IS 'File ID';

COMMENT ON COLUMN "DATASET_COLUMN_PERMISSIONS"."AUTH_TARGET_TYPE" IS '权限类型：组织/角色/用户';

COMMENT ON COLUMN "DATASET_COLUMN_PERMISSIONS"."AUTH_TARGET_ID" IS '权限对象ID';

COMMENT ON COLUMN "DATASET_COLUMN_PERMISSIONS"."DATASET_ID" IS '数据集ID';

COMMENT ON COLUMN "DATASET_COLUMN_PERMISSIONS"."PERMISSIONS" IS '权限';

-- CREATE INDEX "DATAINS_VERSION_S_IDX"
--    ON "DATAINS_VERSION"("SUCCESS");

-- CREATE UNIQUE INDEX "INDEX92974174289932"
--    ON "DATAINS_VERSION"("INSTALLED_RANK");

CREATE INDEX "INDEX92974243033104"
    ON "DATAINS_CODE_VERSION"("SUCCESS");

CREATE UNIQUE INDEX "INDEX92974372866998"
    ON "DATAINS_CODE_VERSION"("INSTALLED_RANK");

CREATE UNIQUE INDEX "INDEX92974423603932"
    ON "CHART_VIEW_CACHE"("ID");



COMMENT ON COLUMN "CHART_VIEW_CACHE"."ID" IS 'ID';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."NAME" IS '名称';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."TITLE" IS 'EChart标题';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."SCENE_ID" IS '场景ID chart_type为private的时候 是仪表板id';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."TABLE_ID" IS '数据集表ID';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."TYPE" IS '图表类型';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."RENDER" IS '视图渲染方式';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."RESULT_COUNT" IS '展示结果';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."RESULT_MODE" IS '展示模式';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."X_AXIS" IS '横轴field';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."X_AXIS_EXT" IS 'table-row';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."Y_AXIS" IS '纵轴field';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."Y_AXIS_EXT" IS '副轴';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."EXT_STACK" IS '堆叠项';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."EXT_BUBBLE" IS '气泡大小';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CUSTOM_ATTR" IS '图形属性';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CUSTOM_STYLE" IS '组件样式';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CUSTOM_FILTER" IS '结果过滤';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."DRILL_FIELDS" IS '钻取字段';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."SENIOR" IS '高级';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."SNAPSHOT" IS '缩略图 ';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."STYLE_PRIORITY" IS '样式优先级 panel 仪表板 view 视图';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."CHART_TYPE" IS '视图类型 public 公共 历史可复用的视图，private 私有 专属某个仪表板';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."IS_PLUGIN" IS '是否插件';

COMMENT ON COLUMN "CHART_VIEW_CACHE"."DATA_FROM" IS '数据来源 template 模板数据 dataset 数据集数据';

CREATE UNIQUE INDEX "INDEX92976047033375"
    ON "CHART_VIEW"("ID");

COMMENT ON COLUMN "CHART_VIEW"."ID" IS 'ID';

COMMENT ON COLUMN "CHART_VIEW"."NAME" IS '名称';

COMMENT ON COLUMN "CHART_VIEW"."TITLE" IS 'EChart标题';

COMMENT ON COLUMN "CHART_VIEW"."SCENE_ID" IS '场景ID chart_type为private的时候 是仪表板id';

COMMENT ON COLUMN "CHART_VIEW"."TABLE_ID" IS '数据集表ID';

COMMENT ON COLUMN "CHART_VIEW"."TYPE" IS '图表类型';

COMMENT ON COLUMN "CHART_VIEW"."RENDER" IS '视图渲染方式';

COMMENT ON COLUMN "CHART_VIEW"."RESULT_COUNT" IS '展示结果';

COMMENT ON COLUMN "CHART_VIEW"."RESULT_MODE" IS '展示模式';

COMMENT ON COLUMN "CHART_VIEW"."X_AXIS" IS '横轴field';

COMMENT ON COLUMN "CHART_VIEW"."X_AXIS_EXT" IS 'table-row';

COMMENT ON COLUMN "CHART_VIEW"."Y_AXIS" IS '纵轴field';

COMMENT ON COLUMN "CHART_VIEW"."Y_AXIS_EXT" IS '副轴';

COMMENT ON COLUMN "CHART_VIEW"."EXT_STACK" IS '堆叠项';

COMMENT ON COLUMN "CHART_VIEW"."EXT_BUBBLE" IS '气泡大小';

COMMENT ON COLUMN "CHART_VIEW"."CUSTOM_ATTR" IS '图形属性';

COMMENT ON COLUMN "CHART_VIEW"."CUSTOM_STYLE" IS '组件样式';

COMMENT ON COLUMN "CHART_VIEW"."CUSTOM_FILTER" IS '结果过滤';

COMMENT ON COLUMN "CHART_VIEW"."DRILL_FIELDS" IS '钻取字段';

COMMENT ON COLUMN "CHART_VIEW"."SENIOR" IS '高级';

COMMENT ON COLUMN "CHART_VIEW"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "CHART_VIEW"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "CHART_VIEW"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "CHART_VIEW"."SNAPSHOT" IS '缩略图 ';

COMMENT ON COLUMN "CHART_VIEW"."STYLE_PRIORITY" IS '样式优先级 panel 仪表板 view 视图';

COMMENT ON COLUMN "CHART_VIEW"."CHART_TYPE" IS '视图类型 public 公共 历史可复用的视图，private 私有 专属某个仪表板';

COMMENT ON COLUMN "CHART_VIEW"."IS_PLUGIN" IS '是否插件';

COMMENT ON COLUMN "CHART_VIEW"."DATA_FROM" IS '数据来源 template 模板数据 dataset 数据集数据';

CREATE UNIQUE INDEX "INDEX92976905327471"
    ON "CHART_GROUP"("ID");

COMMENT ON COLUMN "CHART_GROUP"."ID" IS 'ID';

COMMENT ON COLUMN "CHART_GROUP"."NAME" IS '名称';

COMMENT ON COLUMN "CHART_GROUP"."PID" IS '父级ID';

COMMENT ON COLUMN "CHART_GROUP"."LEVEL" IS '当前分组处于第几级';

COMMENT ON COLUMN "CHART_GROUP"."TYPE" IS 'group or scene';

COMMENT ON COLUMN "CHART_GROUP"."CREATE_BY" IS '创建人ID';

COMMENT ON COLUMN "CHART_GROUP"."CREATE_TIME" IS '创建时间';

CREATE UNIQUE INDEX "INDEX92977180776605"
    ON "AREA_MAPPING"("ID");

COMMENT ON COLUMN "AREA_MAPPING"."ID" IS 'id';

COMMENT ON COLUMN "AREA_MAPPING"."PROVINCE_NAME" IS '省名称';

COMMENT ON COLUMN "AREA_MAPPING"."PROVINCE_CODE" IS '省代码';

COMMENT ON COLUMN "AREA_MAPPING"."CITY_NAME" IS '市名称';

COMMENT ON COLUMN "AREA_MAPPING"."CITY_CODE" IS '市代码';

COMMENT ON COLUMN "AREA_MAPPING"."COUNTY_NAME" IS '县名称';

COMMENT ON COLUMN "AREA_MAPPING"."COUNTY_CODE" IS '县代码';