/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2024 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 7.0.13 */
package io.datains.mybatis.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTSTATEMENTS = 3;
  public int JJTCOLUMN = 4;
  public int JJTTABLENAME = 5;
  public int JJTSELECT = 6;
  public int JJTPARENTHESEDSELECT = 7;
  public int JJTLATERALVIEW = 8;
  public int JJTFORCLAUSE = 9;
  public int JJTLATERALSUBSELECT = 10;
  public int JJTPLAINSELECT = 11;
  public int JJTSETOPERATIONLIST = 12;
  public int JJTWITHITEM = 13;
  public int JJTSELECTITEM = 14;
  public int JJTJOINEREXPRESSION = 15;
  public int JJTLIMITWITHOFFSET = 16;
  public int JJTPLAINLIMIT = 17;
  public int JJTEXPRESSION = 18;
  public int JJTREGULARCONDITION = 19;
  public int JJTINEXPRESSION = 20;
  public int JJTLIKEEXPRESSION = 21;
  public int JJTSIMILARTOEXPRESSION = 22;
  public int JJTISDISTINCTEXPRESSION = 23;
  public int JJTEXPRESSIONLIST = 24;
  public int JJTPRIMARYEXPRESSION = 25;
  public int JJTCONNECTBYROOTOPERATOR = 26;
  public int JJTCASEWHENEXPRESSION = 27;
  public int JJTFUNCTION = 28;
  public int JJTSEQUENCE = 29;
  public int JJTSYNONYM = 30;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Block",
    "Statements",
    "Column",
    "TableName",
    "Select",
    "ParenthesedSelect",
    "LateralView",
    "ForClause",
    "LateralSubSelect",
    "PlainSelect",
    "SetOperationList",
    "WithItem",
    "SelectItem",
    "JoinerExpression",
    "LimitWithOffset",
    "PlainLimit",
    "Expression",
    "RegularCondition",
    "InExpression",
    "LikeExpression",
    "SimilarToExpression",
    "IsDistinctExpression",
    "ExpressionList",
    "PrimaryExpression",
    "ConnectByRootOperator",
    "CaseWhenExpression",
    "Function",
    "Sequence",
    "Synonym",
  };
}
/* JavaCC - OriginalChecksum=d547beb60d9efc44e4938d0fa6ccb38f (do not edit this line) */
