/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2024 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 7.0.13 */
package io.datains.mybatis.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=8d282da9e2b4d64f10389742e27504eb (do not edit this line) */
