/*-
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2024 JSQLParser
 * %%
 * Dual licensed under GNU LGPL 2.1 or Apache License 2.0
 * #L%
 */
/* Generated By:JavaCC: Do not edit this line. Provider.java Version 7.0 */
/* JavaCCOptions:KEEP_LINE_COLUMN=true */
package io.datains.mybatis.jsqlparser.parser;


import java.io.IOException;

public interface Provider {
    /**
     * Reads characters into an array
     * @param buffer  Destination buffer
     * @param offset  Offset at which to start storing characters
     * @param len     The maximum possible number of characters to read
     * @return The number of characters read, or -1 if all read
     * @exception  IOException
     */
    public int read(char buffer[], int offset, int len) throws IOException;

    /**
     * Closes the stream and releases any system resources associated with
     * it.
     * @exception IOException
     */
     public void close() throws IOException;

}
/* JavaCC - OriginalChecksum=f0d1693959036e95e4437315b90f5187 (do not edit this line) */
