const weatherMap = {
  '晴': 'qing',
  '多云': 'duoyun',
  '阴': 'yin',
  '阴天': 'yin',
  '风': 'feng',
  '大风': 'dafeng',
  '飓风': 'jufeng',
  '霾': 'mai',
  '阵雨': 'zhenyu',
  '雷阵雨': 'leizhenyu',
  '小雨': 'xiaoyu',
  '中雨': 'zhongyu',
  '大雨': 'dayu',
  '暴雨': 'baoyu',
  '大暴雨': 'dabaoyu',
  '雨': 'xiaoyu',
  '雨夹雪': 'yujiaxue',
  '雪': 'xiaoxue',
  '阵雪': 'zhenxue',
  '小雪': 'xiaoxue',
  '中雪': 'zhongxue',
  '大雪': 'daxue',
  '浮尘': 'fuchen',
  '扬沙': 'yangsha',
  '沙尘暴': 'shachenbao',
  '雾': 'wu',
  '未知': 'unknow',

  '雷电': 'leidian',
  '冰雹': 'bingbao',
  '霜降': 'shuangjiang',
  '台风': 'taifeng',

  '少云': 'shaoyun',
  '晴间多云': 'qingzhuanduoyun',
  '平静': 'pingjing',
  '微风': 'weifeng',
  '和风': 'hefeng',
  '清风': 'qingfeng',
  '强风/劲风': 'qingfeng',
  '疾风': 'jifeng',
  '烈风': 'liefeng',
  '风暴': 'fengbao',
  '狂爆风': 'kuangbaofeng',
  '热带风暴': 'redaifengbao',
  '中度霾': 'zhongdumai',
  '重度霾': 'zhongdumai (2)',
  '严重霾': 'yanzhongmai',
  '雷阵雨并伴有冰雹': 'leizhenyubingbanyoubingbao',
  '特大暴雨': 'tedabaoyu',
  '强阵雨': 'qiangzhenyu',
  '强雷阵雨': 'qiangleizhenyu',
  '极端降雨': 'jiduanjiangyu',
  '毛毛雨/细雨': 'xiyu',
  '小雨-中雨': 'xiaoyuzhuanzhongyu',
  '中雨-大雨': 'zhongyuzhuandayu',
  '大雨-暴雨': 'dayuzhuanbaoyu',
  '暴雨-大暴雨': 'baoyuzhuandabaoyu',
  '大暴雨-特大暴雨': 'dabaoyuzhuantedabaoyu',
  '雨雪天气': 'yuxuetianqi',
  '阵雨夹雪': 'zhenyujiaxue',
  '冻雨': 'dongyu',
  '暴雪': 'baoxue',
  '小雪-中雪': 'xiaoxuezhuanzhongxue',
  '中雪-大雪': 'zhongxuezhuandaxue',
  '大雪-暴雪': 'daxuezhuanbaoxue',
  '强沙尘暴': 'qiangshachenbao',
  '龙卷风': 'longjuanfeng',
  '浓雾': 'nongwu',
  '强浓雾': 'qiangnongwu',
  '轻雾': 'qingwu',
  '大雾': 'dawu',
  '特强浓雾': 'teqiangnongwu',
  '热': 're',
  '冷': 'leng'

}

export default weatherMap
